call code --install-extension alefragnani.Bookmarks
call code --install-extension donjayamanne.githistory
call code --install-extension donjayamanne.python
call code --install-extension EditorConfig.EditorConfig
call code --install-extension espresso3389.sushi-vscode
call code --install-extension formulahendry.code-runner
call code --install-extension hars.CppSnippets
call code --install-extension ionutvmi.path-autocomplete
call code --install-extension jebbs.plantuml
call code --install-extension michelemelluso.code-beautifier
call code --install-extension ms-vscode.cpptools
call code --install-extension ms-vscode.csharp
call code --install-extension twxs.cmake
call code --install-extension wmaurer.vscode-jumpy
