git:
  branchLogCmd: "git log --graph --color=always --name-status --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}}"
  allBranchesLogCmds:
    - git log --graph --color=always --name-status --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all
  pagers:
    - colorArg: always
      pager: diff-so-fancy
