call code --install-extension alefragnani.Bookmarks
call code --install-extension bbenoist.QML
call code --install-extension donjayamanne.githistory
call code --install-extension EditorConfig.EditorConfig
call code --install-extension formulahendry.code-runner
call code --install-extension hars.CppSnippets
call code --install-extension ionutvmi.path-autocomplete
call code --install-extension liximomo.sftp
call code --install-extension jebbs.plantuml
call code --install-extension michelemelluso.code-beautifier
call code --install-extension ms-python.python
call code --install-extension ms-vscode.cpptools
call code --install-extension ms-vscode.csharp
call code --install-extension pmiossec.vscode-gitextensions
call code --install-extension ryu1kn.annotator
call code --install-extension s-nlf-fh.glassit
call code --install-extension shakram02.bash-beautify
call code --install-extension teabyii.ayu
call code --install-extension twxs.cmake
call code --install-extension wmaurer.vscode-jumpy
