add_newline = false

[character]
success_symbol = "[▶](bold green)"
error_symbol = "[▶](bold red)"

[directory]
truncation_length = 30
truncate_to_repo = false

[git_branch]
symbol = "🌱 "

[git_status]
conflicted = "💥"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🌚"
stashed = "📦"
modified = "📝"
staged = "🔦"
renamed = "🏷"
deleted = "🗑"

[nodejs]
symbol = "⬢ "

[package]
disabled = true

[time]
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true
